supertokens/supertokens-plugin-interface

.github/workflows/lint-pr-title.yml
CHANGELOG.md

Origin PR
* https://github.com/supertokens/supertokens-auth-react/pull/373

ci: add `lint-pr-title.yml` workflow

---

build.gradle

Updates build-gradle
- https://github.com/supertokens/supertokens-plugin-interface/pull/34
- ~~To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.~~
- ~~If no such branch exists, then create one from the latest released branch.~~
- none

chore: updates build.gradle

---

src/main/java/io/supertokens/pluginInterface/thirdparty/ThirdPartyStorage.java
src/main/java/io/supertokens/pluginInterface/thirdparty/ThirdPartyTenantConfig.java
src/main/java/io/supertokens/pluginInterface/thirdparty/exception/DuplicateThirdPartyTenantMappingException.java

Adds interface for third party tenant mapping functions

feat: adds interface for third party tenant mapping

---

src/main/java/io/supertokens/pluginInterface/multitenancy/MultitenancyStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/ThirdPartyConfig.java

fix: changes for multi-tenancy impl

---

src/main/java/io/supertokens/pluginInterface/multitenancy/MultitenancyStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/ThirdPartyConfig.java
src/main/java/io/supertokens/pluginInterface/multitenancy/exceptions/DuplicateClientTypeException.java
src/main/java/io/supertokens/pluginInterface/multitenancy/exceptions/DuplicateThirdPartyIdException.java

fix: new exceptions

---

src/main/java/io/supertokens/pluginInterface/passwordless/sqlStorage/PasswordlessSQLStorage.java

Fixed the interface for passwordless (delete devices by email and phone)

fix: fixed pless interface

---

src/main/java/io/supertokens/pluginInterface/authRecipe/AuthRecipeStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/AppIdentifier.java
src/main/java/io/supertokens/pluginInterface/multitenancy/AppIdentifierWithStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/TenantIdentifier.java
src/main/java/io/supertokens/pluginInterface/multitenancy/TenantIdentifierWithStorage.java
src/main/java/io/supertokens/pluginInterface/useridmapping/UserIdMappingStorage.java

fix: to support PR comments on core

---

src/main/java/io/supertokens/pluginInterface/multitenancy/AppIdentifierWithStorage.java

fix: added storages to appIdentifierWithStorage

---

src/main/java/io/supertokens/pluginInterface/multitenancy/AppIdentifierWithStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/TenantIdentifierWithStorage.java
src/main/java/io/supertokens/pluginInterface/userroles/UserRolesStorage.java
src/main/java/io/supertokens/pluginInterface/userroles/sqlStorage/UserRolesSQLStorage.java

fix: Multitenant userroles

---

src/main/java/io/supertokens/pluginInterface/multitenancy/AppIdentifierWithStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/TenantIdentifierWithStorage.java

fix: Multitenant emailpassword

---

src/main/java/io/supertokens/pluginInterface/multitenancy/AppIdentifierWithStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/TenantIdentifierWithStorage.java

fix: Multitenant passwordless storage

---

src/main/java/io/supertokens/pluginInterface/multitenancy/AppIdentifierWithStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/TenantIdentifierWithStorage.java

fix: thirdparty storage

---

src/main/java/io/supertokens/pluginInterface/multitenancy/AppIdentifierWithStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/TenantIdentifierWithStorage.java

fix: Multitenant emailverification storage

---

src/main/java/io/supertokens/pluginInterface/multitenancy/TenantIdentifierWithStorage.java
src/main/java/io/supertokens/pluginInterface/session/SessionStorage.java
src/main/java/io/supertokens/pluginInterface/session/sqlStorage/SessionSQLStorage.java
src/main/java/io/supertokens/pluginInterface/sqlStorage/SQLStorage.java

fix: Multitenant session

---

src/main/java/io/supertokens/pluginInterface/jwt/sqlstorage/JWTRecipeSQLStorage.java

fix: Multitenant jwt

---

src/main/java/io/supertokens/pluginInterface/multitenancy/AppIdentifierWithStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/TenantIdentifierWithStorage.java

fix: Multitenant Authrecipe changes

---

src/main/java/io/supertokens/pluginInterface/dashboard/DashboardStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/AppIdentifierWithStorage.java

Dashboard changes
- https://github.com/supertokens/supertokens-core/issues/546

fix: Multitenant dashboard

---

src/main/java/io/supertokens/pluginInterface/RECIPE_ID.java
src/main/java/io/supertokens/pluginInterface/multitenancy/EmailPasswordConfig.java
src/main/java/io/supertokens/pluginInterface/multitenancy/MultitenancyStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/TenantConfig.java
src/main/java/io/supertokens/pluginInterface/multitenancy/TenantIdentifierWithStorage.java

- https://github.com/supertokens/supertokens-core/issues/546

fix: multitenancy changes

---

src/main/java/io/supertokens/pluginInterface/multitenancy/TenantIdentifier.java

fix: base tenant in TenantIdentifier

---

src/main/java/io/supertokens/pluginInterface/Storage.java

Adding tenantIdentifier to loadConfig

fix: Startup log

---

src/main/java/io/supertokens/pluginInterface/emailverification/EmailVerificationStorage.java
src/main/java/io/supertokens/pluginInterface/session/SessionStorage.java
src/main/java/io/supertokens/pluginInterface/totp/sqlStorage/TOTPSQLStorage.java

fix: delete non auth user in deleteUserIdFromTenantId

---

src/main/java/io/supertokens/pluginInterface/Storage.java

fix: Delete nonauth user

---

src/main/java/io/supertokens/pluginInterface/Storage.java

fix: Config validation

---

src/main/java/io/supertokens/pluginInterface/multitenancy/TenantConfig.java
src/main/java/io/supertokens/pluginInterface/multitenancy/ThirdPartyConfig.java

fix: reload resources

---

src/main/java/io/supertokens/pluginInterface/Storage.java

fix: appid fkey test

---

src/main/java/io/supertokens/pluginInterface/Storage.java

fix: isTesting in constructor

---

CHANGELOG.md
build.gradle
src/main/java/io/supertokens/pluginInterface/multitenancy/TenantConfig.java

fix: protected config fix

---

src/main/java/io/supertokens/pluginInterface/authRecipe/sqlStorage/AuthRecipeSQLStorage.java

fix: user pagination related

---

src/main/java/io/supertokens/pluginInterface/authRecipe/AuthRecipeUserInfo.java
src/main/java/io/supertokens/pluginInterface/authRecipe/LoginMethod.java

fix: externalUserId in LoginMethod

---

src/main/java/io/supertokens/pluginInterface/authRecipe/AuthRecipeUserInfo.java
src/main/java/io/supertokens/pluginInterface/authRecipe/LoginMethod.java

fix: External userid

---

src/main/java/io/supertokens/pluginInterface/authRecipe/LoginMethod.java

fix: verified not final in LoginMethod

---

src/main/java/io/supertokens/pluginInterface/authRecipe/sqlStorage/AuthRecipeSQLStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/MultitenancyStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/sqlStorage/MultitenancySQLStorage.java

Al user tenant association

---

src/main/java/io/supertokens/pluginInterface/authRecipe/AuthRecipeStorage.java
src/main/java/io/supertokens/pluginInterface/authRecipe/AuthRecipeUserInfo.java

fix: remove con reuse

---

src/main/java/io/supertokens/pluginInterface/ActiveUsersStorage.java
src/main/java/io/supertokens/pluginInterface/authRecipe/AuthRecipeStorage.java

fix: account linking stats

---

src/main/java/io/supertokens/pluginInterface/authRecipe/sqlStorage/AuthRecipeSQLStorage.java
src/main/java/io/supertokens/pluginInterface/useridmapping/sqlStorage/UserIdMappingSQLStorage.java

fix: functions for useridmapping

---

src/main/java/io/supertokens/pluginInterface/ActiveUsersSQLStorage.java
src/main/java/io/supertokens/pluginInterface/ActiveUsersStorage.java
src/main/java/io/supertokens/pluginInterface/mfa/MfaStorage.java
src/main/java/io/supertokens/pluginInterface/mfa/sqlStorage/MfaSQLStorage.java
src/main/java/io/supertokens/pluginInterface/multitenancy/AppIdentifierWithStorage.java

fix: refactor transaction functions

---

src/main/java/io/supertokens/pluginInterface/mfa/MfaStorage.java
src/main/java/io/supertokens/pluginInterface/mfa/sqlStorage/MfaSQLStorage.java

fix: mfa cleanup

---

src/main/java/io/supertokens/pluginInterface/totp/TOTPDevice.java

- https://github.com/supertokens/supertokens-core/issues/554
- https://github.com/supertokens/supertokens-core/pull/651

fix: add createdat to totp device

---

src/main/java/io/supertokens/pluginInterface/ActiveUsersStorage.java
src/main/java/io/supertokens/pluginInterface/authRecipe/AuthRecipeStorage.java

- https://github.com/supertokens/supertokens-core/issues/554
- https://github.com/supertokens/supertokens-core/pull/651

fix: mfa stats

---

CHANGELOG.md
build.gradle
src/main/java/io/supertokens/pluginInterface/emailverification/EmailVerificationStorage.java

fix: email verification fix with user id mapping

---

CHANGELOG.md
build.gradle
src/main/java/io/supertokens/pluginInterface/session/noSqlStorage/SessionNoSQLStorage_1.java
src/main/java/io/supertokens/pluginInterface/session/sqlStorage/SessionSQLStorage.java
src/main/java/io/supertokens/pluginInterface/useridmapping/UserIdMappingStorage.java

fix: backports for core 8.0

---

CHANGELOG.md
build.gradle
src/main/java/io/supertokens/pluginInterface/session/noSqlStorage/SessionNoSQLStorage_1.java
src/main/java/io/supertokens/pluginInterface/session/sqlStorage/SessionSQLStorage.java
src/main/java/io/supertokens/pluginInterface/useridmapping/UserIdMappingStorage.java

fix: backports to core 7.0

---

CHANGELOG.md
build.gradle
src/main/java/io/supertokens/pluginInterface/Storage.java

fix: backport 8.0.3

---

CHANGELOG.md
src/main/java/io/supertokens/pluginInterface/multitenancy/EmailPasswordConfig.java
src/main/java/io/supertokens/pluginInterface/multitenancy/PasswordlessConfig.java
src/main/java/io/supertokens/pluginInterface/multitenancy/TenantConfig.java
src/main/java/io/supertokens/pluginInterface/multitenancy/ThirdPartyConfig.java

feat: multitenancy dashboard

---

CHANGELOG.md
build.gradle
src/main/java/io/supertokens/pluginInterface/Storage.java
src/main/java/io/supertokens/pluginInterface/StorageUtils.java
src/main/java/io/supertokens/pluginInterface/authRecipe/AuthRecipeStorage.java
src/main/java/io/supertokens/pluginInterface/authRecipe/sqlStorage/AuthRecipeSQLStorage.java
src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportStorage.java
src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportUser.java
src/main/java/io/supertokens/pluginInterface/bulkimport/ImportUserBase.java
src/main/java/io/supertokens/pluginInterface/bulkimport/exceptions/BulkImportBatchInsertException.java
src/main/java/io/supertokens/pluginInterface/bulkimport/exceptions/BulkImportTransactionRolledBackException.java
src/main/java/io/supertokens/pluginInterface/bulkimport/exceptions/DuplicateUserIdException.java
src/main/java/io/supertokens/pluginInterface/bulkimport/sqlStorage/BulkImportSQLStorage.java
src/main/java/io/supertokens/pluginInterface/emailpassword/EmailPasswordImportUser.java
src/main/java/io/supertokens/pluginInterface/emailpassword/sqlStorage/EmailPasswordSQLStorage.java
src/main/java/io/supertokens/pluginInterface/emailverification/EmailVerificationStorage.java
src/main/java/io/supertokens/pluginInterface/emailverification/sqlStorage/EmailVerificationSQLStorage.java
src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessImportUser.java
src/main/java/io/supertokens/pluginInterface/passwordless/sqlStorage/PasswordlessSQLStorage.java
src/main/java/io/supertokens/pluginInterface/sqlStorage/SQLStorage.java
src/main/java/io/supertokens/pluginInterface/thirdparty/ThirdPartyImportUser.java
src/main/java/io/supertokens/pluginInterface/thirdparty/sqlStorage/ThirdPartySQLStorage.java
src/main/java/io/supertokens/pluginInterface/totp/sqlStorage/TOTPSQLStorage.java
src/main/java/io/supertokens/pluginInterface/useridmapping/UserIdMappingStorage.java
src/main/java/io/supertokens/pluginInterface/useridmapping/sqlStorage/UserIdMappingSQLStorage.java
src/main/java/io/supertokens/pluginInterface/usermetadata/sqlStorage/UserMetadataSQLStorage.java
src/main/java/io/supertokens/pluginInterface/userroles/sqlStorage/UserRolesSQLStorage.java

* feat: Add BulkImport APIs and cron
* fix: PR changes
* fix: PR changes
* fix: Update version and changelog
* fix: PR changes
* fix: PR changes
* fix: fixing transaction rolled back issues with multithreaded bulk import
* fix: changelog
* fix: reusing gson object
* feat: bulk inserting the bulk migration data
* fix: fixes and error handling changes
* fix: fixing tests
* chore: update build version and changelog
* fix: adding exeption thrown declaration for bulk import and mysql
---------
- If no …

feat: multithreaded bulk import (#162)

---

CHANGELOG.md
build.gradle

fix: version update

---

src/main/java/io/supertokens/pluginInterface/StorageUtils.java
src/main/java/io/supertokens/pluginInterface/webauthn/AccountRecoveryTokenInfo.java
src/main/java/io/supertokens/pluginInterface/webauthn/DuplicateRecoverAccountTokenException.java
src/main/java/io/supertokens/pluginInterface/webauthn/WebAuthNStorage.java
src/main/java/io/supertokens/pluginInterface/webauthn/slqStorage/WebAuthNSQLStorage.java

feat: webauthn - account recovery

---

src/main/java/io/supertokens/pluginInterface/authRecipe/AuthRecipeUserInfo.java
src/main/java/io/supertokens/pluginInterface/dashboard/DashboardSearchTags.java

fix: user json and dashboard search

---

src/main/java/io/supertokens/pluginInterface/webauthn/WebAuthNStorage.java
src/main/java/io/supertokens/pluginInterface/webauthn/exceptions/DuplicateCredentialException.java
src/main/java/io/supertokens/pluginInterface/webauthn/exceptions/DuplicateOptionsIdException.java
src/main/java/io/supertokens/pluginInterface/webauthn/slqStorage/WebAuthNSQLStorage.java

fix: webauthn review fixes

---

CHANGELOG.md
build.gradle
src/main/java/io/supertokens/pluginInterface/RECIPE_ID.java
src/main/java/io/supertokens/pluginInterface/StorageUtils.java
src/main/java/io/supertokens/pluginInterface/authRecipe/AuthRecipeStorage.java
src/main/java/io/supertokens/pluginInterface/authRecipe/AuthRecipeUserInfo.java
src/main/java/io/supertokens/pluginInterface/authRecipe/LoginMethod.java
src/main/java/io/supertokens/pluginInterface/authRecipe/sqlStorage/AuthRecipeSQLStorage.java
src/main/java/io/supertokens/pluginInterface/dashboard/DashboardSearchTags.java
src/main/java/io/supertokens/pluginInterface/webauthn/AccountRecoveryTokenInfo.java
src/main/java/io/supertokens/pluginInterface/webauthn/WebAuthNOptions.java
src/main/java/io/supertokens/pluginInterface/webauthn/WebAuthNStorage.java
src/main/java/io/supertokens/pluginInterface/webauthn/WebAuthNStoredCredential.java
src/main/java/io/supertokens/pluginInterface/webauthn/exceptions/DuplicateCredentialException.java
src/main/java/io/supertokens/pluginInterface/webauthn/exceptions/DuplicateOptionsIdException.java
src/main/java/io/supertokens/pluginInterface/webauthn/exceptions/DuplicateRecoverAccountTokenException.java
src/main/java/io/supertokens/pluginInterface/webauthn/exceptions/DuplicateUserEmailException.java
src/main/java/io/supertokens/pluginInterface/webauthn/exceptions/DuplicateUserIdException.java
src/main/java/io/supertokens/pluginInterface/webauthn/exceptions/UserIdNotFoundException.java
src/main/java/io/supertokens/pluginInterface/webauthn/exceptions/WebauthNCredentialNotExistsException.java
src/main/java/io/supertokens/pluginInterface/webauthn/exceptions/WebauthNOptionsNotExistsException.java
src/main/java/io/supertokens/pluginInterface/webauthn/slqStorage/WebAuthNSQLStorage.java

Adds webauthn (passkeys) support to core.

feat: webauthn 

---

CHANGELOG.md
build.gradle

feat: java gradle upgrade

---

CHANGELOG.md
src/main/java/io/supertokens/pluginInterface/Storage.java

fix: update config from env
