- CHANGELOG.md
- build.gradle
- src/main/java/io/supertokens/pluginInterface/sqlStorage/SQLStorage.java
Allowing a lower transaction isolation level we can use in pwless createDeviceWithCode
> feat: allow transactions w/ lower isolation level

- src/main/java/io/supertokens/pluginInterface/userroles/sqlStorage/UserRolesSQLStorage.java
- Renames `addPermissionToRole_Transaction` -> `addPermissionToRoleOrDoNothingIfExists_Transaction`
- https://github.com/supertokens/supertokens-plugin-interface/pull/34
- none
> fix: renames addPermissionToRole function

- src/main/java/io/supertokens/pluginInterface/userroles/UserRolesStorage.java
- src/main/java/io/supertokens/pluginInterface/userroles/sqlStorage/UserRolesSQLStorage.java
Updating the  `createNewRoleOrDoNothingIfExists_Transaction` to return a `boolean` so we know if any rows are updated when creating a role or adding a role to a user. This change is due to the discussion mentioned
- https://github.com/supertokens/supertokens-core/issues/382#issuecomment-1102458937
- ~~[ ] Changelog has been updated~~
- ~~[ ] Changes to the version if needed~~
- ~~In `build.gradle`~~
- ~~[ ] Issue this PR against the latest non released version branch.~~
- ~~To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.~~
- ~~If no such branch exists, then create one from the latest released branch.~~
- none
> fix: updates function signitures

- CHANGELOG.md
Updates CHANGELOG.md
- https://github.com/supertokens/supertokens-plugin-interface/pull/34
- ~~In `build.gradle`~~
- ~~To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.~~
- ~~If no such branch exists, then create one from the latest released branch.~~
- none
> chore: updates changelog

- CHANGELOG.md
- build.gradle
- src/main/java/io/supertokens/pluginInterface/Storage.java
- src/main/java/io/supertokens/pluginInterface/emailverification/EmailVerificationStorage.java
- src/main/java/io/supertokens/pluginInterface/jwt/JWTRecipeStorage.java
- src/main/java/io/supertokens/pluginInterface/nonAuthRecipe/NonAuthRecipeStorage.java
- src/main/java/io/supertokens/pluginInterface/session/SessionStorage.java
- src/main/java/io/supertokens/pluginInterface/useridmapping/UserIdMappingStorage.java
- src/main/java/io/supertokens/pluginInterface/userroles/UserRolesStorage.java
> feat: adds addtional function for userIdmapping

- CHANGELOG.md
- src/main/java/io/supertokens/pluginInterface/thirdparty/exception/DuplicateThirdPartyUserException.java
- src/main/java/io/supertokens/pluginInterface/thirdparty/exception/DuplicateUserIdException.java
- src/main/java/io/supertokens/pluginInterface/thirdparty/exception/ThirdPartyException.java
Fixs exception extended by third-party recipe
- https://github.com/supertokens/supertokens-plugin-interface/issues/47
> fix: corrects thirdparty exceptions

- CHANGELOG.md
- build.gradle
Because we want to make sure new plugins only work with new core - cause of dependency changes
- https://github.com/supertokens/supertokens-core/issues/525
> Updates version

- CHANGELOG.md
- src/main/java/io/supertokens/pluginInterface/ActiveUsersStorage.java
Add plugin interface for active users storage layer
- See TODO section of https://github.com/supertokens/supertokens-core/pull/564
> feat: Add plugin interface for active users storage layer

- src/main/java/io/supertokens/pluginInterface/emailverification/EmailVerificationStorage.java
- src/main/java/io/supertokens/pluginInterface/emailverification/sqlStorage/EmailVerificationSQLStorage.java
> fix: making tokens tenant specific

- src/main/java/io/supertokens/pluginInterface/multitenancy/TenantIdentifierWithStorage.java
- src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
- src/main/java/io/supertokens/pluginInterface/totp/sqlStorage/TOTPSQLStorage.java
- https://github.com/supertokens/supertokens-core/issues/546
> fix: Multitenant totp

- src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Client.java
- src/main/java/io/supertokens/pluginInterface/oauth2/sqlStorage/OAuth2SQLStorage.java
Added missing exception on `oauth2CreateClient` method and changes method signature.
- https://github.com/supertokens/supertokens-core/issues/582
> feat: Added missing exception on Oauth2 methods

- src/main/java/io/supertokens/pluginInterface/oauth2/exception/DuplicateOAuth2ClientNameException.java
- src/main/java/io/supertokens/pluginInterface/oauth2/sqlStorage/OAuth2SQLStorage.java
Added new exception for Client name uniqueness
- https://github.com/supertokens/supertokens-core/issues/582
> fix: added new exception for uniqueness of client name

- CHANGELOG.md
- build.gradle
- src/main/java/io/supertokens/pluginInterface/multitenancy/TenantConfig.java
- src/main/java/io/supertokens/pluginInterface/multitenancy/ThirdPartyConfig.java
> fix: tenant config clone

- CHANGELOG.md
- build.gradle
- src/main/java/io/supertokens/pluginInterface/authRecipe/AuthRecipeUserInfo.java
Removes the error `Please use a CDI version that is greater than the one in which account linking feature was enabled` while querying users with linked accounts, but from an older version of CDI. We return details of the oldest login method in this case.
> fix: query user with linked account from older CDI

- CHANGELOG.md
- src/main/java/io/supertokens/pluginInterface/session/noSqlStorage/SessionNoSQLStorage_1.java
- src/main/java/io/supertokens/pluginInterface/session/sqlStorage/SessionSQLStorage.java
Add support to update the signing key type of a session
- core: https://github.com/supertokens/supertokens-core/pull/909
- plugin-interface: https://github.com/supertokens/supertokens-plugin-interface/pull/136
- postgresql-plugin: https://github.com/supertokens/supertokens-postgresql-plugin/pull/180
- mysql-plugin: https://github.com/supertokens/supertokens-mysql-plugin/pull/88
- mongodb-plugin: https://github.com/supertokens/supertokens-mongodb-plugin/pull/31
- node: https://github.com/supertokens/supertokens-node/pull/782
- If no such branch exists, then create one …
> feat: Add support to update the signing key type of a session

- CHANGELOG.md
- build.gradle
- src/main/java/io/supertokens/pluginInterface/ConfigFieldInfo.java
- src/main/java/io/supertokens/pluginInterface/Storage.java
Adds a new method to the interface to fetch the config of the plugin as json
N/A
N/A
> feat: Add a new method to fetch the config as json

- CHANGELOG.md
- build.gradle
- src/main/java/io/supertokens/pluginInterface/Storage.java
- https://github.com/supertokens/supertokens-core/issues/982
> fix: core db crash

- src/main/java/io/supertokens/pluginInterface/oauth/OAuthLogoutChallenge.java
- src/main/java/io/supertokens/pluginInterface/oauth/OAuthStorage.java
> fix: logout

- src/main/java/io/supertokens/pluginInterface/oauth/OAuthStorage.java
Changing method signature, there is no need for it to handle list of JTIs. This simplifies the interface and the underlying implementation.
> fix: jti listing

- src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportStorage.java
- src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportUser.java
> fix: fixing tests

- CHANGELOG.md
- build.gradle
- src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportUser.java
support for "bulk migration returns user ids"
> feat: bulk migration return userids

- CHANGELOG.md
- build.gradle
- implementationDependencies.json
> chore: remove implementationdependencies json
